blank_issues_enabled: false
contact_links:
  - name: 💬 General Question
    url: https://github.com/aws-samples/djrlj694/aws-cdk-python-workshop/discussions/categories/q-a
    about: Please ask and answer questions as a discussion thread
